name: Deploy WordPress
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H your_server_ip >> ~/.ssh/known_hosts
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Sync files to server
      run: rsync -avz --delete ./ kane@20.2.86.192:/www/wordpress